openapi: 3.2.0
info:
  title: Fast User API
  version: 0.1.0
tags:
- name: User
paths:
  /user:
    get:
      summary: Get Authenticated User
      operationId: get_authenticated_user_user_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseModel_Dict_'
      security:
      - HTTPBearer: []
      tags:
      - User
    patch:
      summary: Update Authenticated User
      operationId: update_authenticated_user_user_patch
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAuthenticatedUserRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseModel_Dict_'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - HTTPBearer: []
      tags:
      - User
components:
  schemas:
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    ResponseModel_Dict_:
      properties:
        success:
          type: boolean
          title: Success
          default: true
        error_msg:
          type: string
          title: Error Msg
        data:
          type: object
          title: Data
        count:
          type: integer
          title: Count
      type: object
      title: ResponseModel[Dict]
    UpdateAuthenticatedUserRequest:
      properties:
        name:
          type: string
          title: Name
        picture:
          type: string
          title: Picture
        team:
          type: string
          title: Team
      type: object
      title: UpdateAuthenticatedUserRequest
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
