openapi: 3.2.0
info:
  title: Fast Labs API
  version: 0.1.0
tags:
- name: Labs
paths:
  /labs/label:
    post:
      summary: Label
      operationId: label_labs_label_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LabsRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseModel'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      tags:
      - Labs
  /labs/feedback:
    post:
      summary: Collect Feedback
      operationId: collect_feedback_labs_feedback_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LabsFeedback'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseModel'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      tags:
      - Labs
components:
  schemas:
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    ResponseModel:
      properties:
        success:
          type: boolean
          title: Success
          default: true
        error_msg:
          type: string
          title: Error Msg
        data:
          title: Data
        count:
          type: integer
          title: Count
      type: object
      title: ResponseModel
    LabsFeedback:
      properties:
        session_id:
          type: string
          title: Session Id
        comparison_id:
          type: string
          title: Comparison Id
        referrer:
          type: string
          title: Referrer
        task_type:
          type: string
          title: Task Type
        guidelines:
          type: string
          title: Guidelines
        labels:
          items:
            type: string
          type: array
          title: Labels
        context:
          type: string
          title: Context
        input:
          type: string
          title: Input
        llm_labels:
          items:
            type: object
          type: array
          title: Llm Labels
        feedback:
          type: integer
          title: Feedback
      type: object
      required:
      - task_type
      - guidelines
      - input
      - llm_labels
      - feedback
      title: LabsFeedback
    LabsRequest:
      properties:
        session_id:
          type: string
          title: Session Id
        comparison_id:
          type: string
          title: Comparison Id
        referrer:
          type: string
          title: Referrer
        task_type:
          type: string
          title: Task Type
        guidelines:
          type: string
          title: Guidelines
        labels:
          items:
            type: string
          type: array
          title: Labels
        context:
          type: string
          title: Context
        input:
          type: string
          title: Input
        model:
          type: string
          title: Model
      type: object
      required:
      - task_type
      - guidelines
      - input
      - model
      title: LabsRequest
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
