openapi: 3.2.0
info:
  title: Fast Webhooks API
  version: 0.1.0
tags:
- name: Webhooks
paths:
  /webhooks/{webhook_id}/events:
    post:
      summary: Process Webhook Event
      description: Process incoming webhook events
      operationId: process_webhook_event_webhooks__webhook_id__events_post
      parameters:
      - required: true
        schema:
          type: string
          title: Webhook Id
        name: webhook_id
        in: path
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AirbyteWebhookRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      tags:
      - Webhooks
components:
  schemas:
    AirbyteWebhookRequest:
      properties:
        text:
          type: string
          title: Text
        blocks:
          items:
            type: object
          type: array
          title: Blocks
          default: []
        data:
          type: object
          title: Data
          default: {}
      type: object
      required:
      - text
      title: AirbyteWebhookRequest
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    WebhookResponse:
      properties:
        status:
          type: integer
          title: Status
        error:
          type: string
          title: Error
      type: object
      required:
      - status
      title: WebhookResponse
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
