openapi: 3.2.0
info:
  title: Fast Teams API
  version: 0.1.0
tags:
- name: Teams
paths:
  /teams:
    get:
      summary: Get Teams
      operationId: get_teams_teams_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseModel_List_refuel_cloud_core.schemas.team.TeamSchema__'
      security:
      - HTTPBearer: []
      tags:
      - Teams
components:
  schemas:
    APIUsage:
      properties:
        quota:
          type: integer
          title: Quota
        monthly_quota:
          type: integer
          title: Monthly Quota
        monthly_usage:
          type: integer
          title: Monthly Usage
          default: 0
      type: object
      required:
      - quota
      title: APIUsage
    ResponseModel_List_refuel_cloud_core.schemas.team.TeamSchema__:
      properties:
        success:
          type: boolean
          title: Success
          default: true
        error_msg:
          type: string
          title: Error Msg
        data:
          items:
            $ref: '#/components/schemas/TeamSchema'
          type: array
          title: Data
        count:
          type: integer
          title: Count
      type: object
      title: ResponseModel[List[refuel_cloud_core.schemas.team.TeamSchema]]
    TeamSchema:
      properties:
        name:
          type: string
          title: Name
        integrations:
          type: object
          title: Integrations
          default: {}
        web_app:
          type: object
          title: Web App
          default: {}
        llm_config:
          type: object
          title: Llm Config
          default: {}
        api_key:
          type: string
          title: Api Key
        api_key_sha:
          type: string
          title: Api Key Sha
        api_usage:
          $ref: '#/components/schemas/APIUsage'
        created_at:
          type: string
          format: date-time
          title: Created At
        email_domain:
          type: string
          title: Email Domain
        feature_flags:
          type: object
          title: Feature Flags
          default: {}
      type: object
      required:
      - name
      title: TeamSchema
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
