openapi: 3.2.0
info:
  title: Fast Usage API
  version: 0.1.0
tags:
- name: Usage
paths:
  /usage:
    get:
      summary: Get Team Usage
      operationId: get_team_usage_usage_get
      parameters:
      - required: false
        schema:
          type: string
          title: Start Date
        name: start_date
        in: query
      - required: false
        schema:
          type: string
          title: End Date
        name: end_date
        in: query
      - required: false
        schema:
          type: string
          title: Application Id
        name: application_id
        in: query
      - required: false
        schema:
          type: string
          title: Task Id
        name: task_id
        in: query
      - required: false
        schema:
          type: string
          title: Model
        name: model
        in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseModel'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - HTTPBearer: []
      tags:
      - Usage
components:
  schemas:
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    ResponseModel:
      properties:
        success:
          type: boolean
          title: Success
          default: true
        error_msg:
          type: string
          title: Error Msg
        data:
          title: Data
        count:
          type: integer
          title: Count
      type: object
      title: ResponseModel
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
