openapi: 3.2.0
info:
  title: Fast Models API
  version: 0.1.0
tags:
- name: Models
paths:
  /models:
    get:
      summary: Get Models
      description: 'Get available models for a team.


        Args:

        ----

        token: Authentication token containing team info


        Returns:

        -------

        ResponseModel: List of available models'
      operationId: get_models_models_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseModel_List_'
      security:
      - HTTPBearer: []
      tags:
      - Models
components:
  schemas:
    ResponseModel_List_:
      properties:
        success:
          type: boolean
          title: Success
          default: true
        error_msg:
          type: string
          title: Error Msg
        data:
          items: {}
          type: array
          title: Data
        count:
          type: integer
          title: Count
      type: object
      title: ResponseModel[List]
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
