openapi: 3.2.0
info:
  title: Fast Finetuned Models API
  version: 0.1.0
tags:
- name: Finetuned Models
paths:
  /finetuned_models/{model_id}:
    get:
      summary: Get Finetuned Model From Id
      description: Gets the training status for a finetuned model.
      operationId: get_finetuned_model_from_id_finetuned_models__model_id__get
      parameters:
      - required: true
        schema:
          type: string
          title: Model Id
        name: model_id
        in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - HTTPBearer: []
      tags:
      - Finetuned Models
    delete:
      summary: Delete Finetuned Model From Id
      description: Deletes a finetuned model.
      operationId: delete_finetuned_model_from_id_finetuned_models__model_id__delete
      parameters:
      - required: true
        schema:
          type: string
          title: Model Id
        name: model_id
        in: path
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - HTTPBearer: []
      tags:
      - Finetuned Models
    patch:
      summary: Update Finetuned Model
      description: Update an existing finetuned model.
      operationId: update_finetuned_model_finetuned_models__model_id__patch
      parameters:
      - required: true
        schema:
          type: string
          title: Model Id
        name: model_id
        in: path
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EditModelRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - HTTPBearer: []
      tags:
      - Finetuned Models
components:
  schemas:
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    UserAction:
      type: string
      enum:
      - STARTED
      - INTERRUPTED
      title: UserAction
      description: An enumeration.
    EditModelRequest:
      properties:
        availability_status:
          $ref: '#/components/schemas/AvailabilityStatus'
        finetuning_run_status:
          $ref: '#/components/schemas/UserAction'
      type: object
      title: EditModelRequest
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    AvailabilityStatus:
      type: string
      enum:
      - UNAVAILABLE
      - AVAILABLE
      title: AvailabilityStatus
      description: An enumeration.
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
