openapi: 3.2.0
info:
  title: Fast Webhook API
  version: 0.1.0
tags:
- name: Webhook
paths:
  /webhook/events:
    post:
      summary: Process Event
      description: Process incoming webhook events
      operationId: process_event_webhook_events_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebhookEventRequest'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebhookResponse'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - HTTPBearer: []
      tags:
      - Webhook
components:
  schemas:
    WebhookEventCategory:
      type: string
      enum:
      - aws
      - datasaur
      title: WebhookEventCategory
      description: An enumeration.
    DatasaurEventType:
      type: string
      enum:
      - project_created
      title: DatasaurEventType
      description: An enumeration.
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    AWSEventType:
      type: string
      enum:
      - s3_file_uploaded
      title: AWSEventType
      description: An enumeration.
    DatasaurProjectCreationPayload:
      properties:
        project_id:
          type: string
          title: Project Id
        project_name:
          type: string
          title: Project Name
        refuel_task_name:
          type: string
          title: Refuel Task Name
      type: object
      required:
      - project_id
      - refuel_task_name
      title: DatasaurProjectCreationPayload
    WebhookEventRequest:
      properties:
        event_type:
          anyOf:
          - $ref: '#/components/schemas/DatasaurEventType'
          - $ref: '#/components/schemas/AWSEventType'
          title: Event Type
        event_category:
          $ref: '#/components/schemas/WebhookEventCategory'
        payload:
          anyOf:
          - $ref: '#/components/schemas/DatasaurProjectCreationPayload'
          - $ref: '#/components/schemas/AWSS3FileUploadedPayload'
          title: Payload
      type: object
      required:
      - event_type
      - event_category
      - payload
      title: WebhookEventRequest
    WebhookResponse:
      properties:
        status:
          type: integer
          title: Status
        error:
          type: string
          title: Error
      type: object
      required:
      - status
      title: WebhookResponse
    AWSS3FileUploadedPayload:
      properties:
        dataset:
          type: string
          title: Dataset
        project:
          type: string
          title: Project
        s3_path:
          type: string
          title: S3 Path
        task:
          type: string
          title: Task
      type: object
      required:
      - dataset
      - project
      - s3_path
      - task
      title: AWSS3FileUploadedPayload
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
