openapi: 3.2.0
info:
  title: Fast Schema API
  version: 0.1.0
tags:
- name: Schema
paths:
  /schema:
    post:
      summary: Validate Schema
      description: 'Validate a schema string and return an example if valid.


        Args:

        ----

        schema: The schema string to validate

        token: Access token for authentication


        Returns:

        -------

        ResponseModel containing a valid example if schema is valid


        Raises:

        ------

        HTTPException: If schema is invalid or validation fails'
      operationId: validate_schema_schema_post
      parameters:
      - required: true
        schema:
          type: string
          title: Schema
        name: schema
        in: query
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResponseModel'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      security:
      - HTTPBearer: []
      tags:
      - Schema
components:
  schemas:
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    ResponseModel:
      properties:
        success:
          type: boolean
          title: Success
          default: true
        error_msg:
          type: string
          title: Error Msg
        data:
          title: Data
        count:
          type: integer
          title: Count
      type: object
      title: ResponseModel
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
  securitySchemes:
    HTTPBearer:
      type: http
      scheme: bearer
